exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - package.json
  - package-lock.json
  - script
  - src

remote_theme: marella/jekyll-theme-documentation

permalink: pretty
nav:
  - Введение:
    - Введение: 'content/introduction/introduction'
    - Что такое Java: 'content/introduction/what-is-java'
    - Структура книги: 'content/introduction/book-structure'
  - Глава 1. Встроенные типы данных операции над ними:
    - Первая программа на Java: 'content/chapter-1/first-programm-on-java'
  - Глава 2. Объектно-ориентированное программирование в Java:
    - Парадигмы программирования: 'content/chapter-2/paradigmy-programmirovaniya'
    - Принципы объектно-ориентированного программирования: 'content/chapter-2/principy-object-oriented-programming'
    - Абстракция: 'content/chapter-2/abstraction'
    - Как описать класс и подкласс?: 'content/chapter-2/kak-opisat-klass-i-podklass'
    - Передача параметров в метод: 'content/chapter-2/peredacha-parametrov-v-metod'
    - Перегрузка методов: 'content/chapter-2/peregruzka-metodov'
  - Демонстрация:
    - Markdown: demos/markdown
    - Другая страница: demos/another-page
    - Оглавление: demos/toc
